# Note: this playbook can't run independently

- hosts: "{{ NODE_TO_ADD }}" 
  roles:
  - { role: os-harden, when: "OS_HARDEN|bool" }
  - { role: chrony, when: "groups['chrony']|length > 0" } 
  - prepare
  - { role: docker, when: "CONTAINER_RUNTIME == 'docker'" }
  - { role: containerd, when: "CONTAINER_RUNTIME == 'containerd'" }
  - kube-lb
  - kube-master
  - kube-node
  #
  tasks:
  - name: Making master nodes SchedulingDisabled
    shell: "{{ base_dir }}/bin/kubectl cordon {{ NODE_TO_ADD }} "
    when: "inventory_hostname not in groups['kube_node']"
    ignore_errors: true
    connection: local

  - name: Setting master role name
    shell: "{{ base_dir }}/bin/kubectl label node {{ NODE_TO_ADD }} kubernetes.io/role=master --overwrite"
    ignore_errors: true
    connection: local
