- name: 获取是否已经安装containerd
  shell: 'systemctl is-active containerd || echo "NoFound"'
  register: containerd_svc

- block:
    - name: 准备containerd相关目录
      file: name={{ item }} state=directory
      with_items:
      - "{{ bin_dir }}"
      - "/etc/containerd"

    - name: 加载内核模块 overlay
      modprobe: name=overlay state=present

    - name: 下载 containerd 二进制文件
      copy: src={{ base_dir }}/bin/containerd-bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
      with_items:
      - containerd
      - containerd-shim
      - containerd-shim-runc-v1
      - containerd-shim-runc-v2
      - crictl
      - ctr
      - runc
      tags: upgrade

    - name: 创建 containerd 配置文件
      template: src=config.toml.j2 dest=/etc/containerd/config.toml
      tags: upgrade

    - name: Define 'harbor_hostname', a domain name
      set_fact: harbor_hostname={{ HARBOR_DOMAIN }}
      when: "HARBOR_DOMAIN != ''"

    - name: Define 'harbor_hostname', an IP Addr
      set_fact: harbor_hostname={{ groups['harbor'][0] }}
      when: "HARBOR_DOMAIN == ''"

    - name: 准备证书相关目录
      file: name={{ item }} state=directory
      with_items:
      - "/etc/containerd/certs.d/{{ harbor_hostname }}"

    - name: 创建 harbor 配置文件
      template: src=hosts.toml.j2 dest=/etc/containerd/certs.d/{{ harbor_hostname }}/hosts.toml
      tags: upgrade

    - name: 拷贝 CA 公钥
      template: src=ca.crt.j2 dest=/etc/containerd/certs.d/{{ harbor_hostname }}/ca.crt
      tags: upgrade

    - name: 准备证书相关目录
      file: name={{ item }} state=directory
      with_items:
      - "/etc/containerd/certs.d/132.252.37.116:443"
      - "/etc/containerd/certs.d/docker.io"
      when: "ENABLE_MIRROR_REGISTRY == true"

    - name: 创建 harbor 配置文件
      template: src=hosts.mirror.toml.j2 dest=/etc/containerd/certs.d/132.252.37.116:443/hosts.toml
      tags: upgrade
      when: "ENABLE_MIRROR_REGISTRY == true"

    - name: 创建 harbor 配置文件
      template: src=hosts.mirror.toml.j2 dest=/etc/containerd/certs.d/docker.io/hosts.toml
      tags: upgrade
      when: "ENABLE_MIRROR_REGISTRY == true"

    - name: 创建systemd unit文件
      template: src=containerd.service.j2 dest=/etc/systemd/system/containerd.service
      tags: upgrade

    - name: 创建 crictl 配置
      template: src=crictl.yaml.j2 dest=/etc/crictl.yaml

    - name: 开机启用 containerd 服务
      shell: systemctl enable containerd
      ignore_errors: true

    - name: 开启 containerd 服务
      shell: systemctl daemon-reload && systemctl restart containerd
      tags: upgrade

    - name: 轮询等待containerd服务运行
      shell: "systemctl is-active containerd.service"
      register: containerd_status
      until: '"active" in containerd_status.stdout'
      retries: 8
      delay: 2
      tags: upgrade
  when: "'NoFound' in containerd_svc.stdout"
